name: Synchronize to forked repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0

      - name: Add remote forked-repo
        run: |
          git remote add forked-repo https://minij02:${{ secrets.AUTO_ACTIONS }}@github.com/minij02/4th-security-S4-FE.git
          git config user.name "minij02"
          git config user.email "${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}"

      - name: Push to fork
        run: git push -f forked-repo main

      - name: Clean up
        run: git remote remove forked-repo